# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample-image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample-image.proto',
  package='pictures.luminostics.lab.research',
  syntax='proto3',
  serialized_options=b'\n\'pictures.luminostics.lab.research.modelB\tLabImagesP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12sample-image.proto\x12!pictures.luminostics.lab.research\"i\n\x0fSparseBsrMatrix\x12\x12\n\nblockWidth\x18\x03 \x01(\r\x12\x13\n\x0b\x62lockHeight\x18\x04 \x01(\r\x12\x0e\n\x06indPtr\x18\x06 \x03(\r\x12\x0f\n\x07indices\x18\x08 \x03(\r\x12\x0c\n\x04\x64\x61ta\x18\n \x03(\r\"\xa7\x01\n\x15\x42inarySparseBsrMatrix\x12\x12\n\nblockWidth\x18\x03 \x01(\r\x12\x13\n\x0b\x62lockHeight\x18\x04 \x01(\r\x12\x11\n\tindPtrLen\x18\x05 \x01(\r\x12\x0e\n\x06indPtr\x18\x06 \x01(\x0c\x12\x12\n\nindicesLen\x18\x07 \x01(\r\x12\x0f\n\x07indices\x18\x08 \x01(\x0c\x12\x0f\n\x07\x64\x61taLen\x18\t \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\n \x01(\x0c\"$\n\x14\x44\x65nseFlattenedMatrix\x12\x0c\n\x04\x64\x61ta\x18\n \x03(\r\";\n\x1a\x42inaryDenseFlattenedMatrix\x12\x0f\n\x07\x64\x61taLen\x18\t \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\n \x01(\x0c\"s\n\x10XmpHeaderContent\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61taType\x18\x0c \x01(\t\x12\x13\n\x0b\x63\x61ptureTime\x18\r \x01(\x01\x12\x14\n\x0c\x63\x61ptureDelay\x18\x0e \x01(\x02\x12\x14\n\x0c\x65xposureTime\x18\x0f \x01(\x02\"\xed\x03\n\x14ImageSampleContainer\x12\x43\n\x06header\x18\x01 \x01(\x0b\x32\x33.pictures.luminostics.lab.research.XmpHeaderContent\x12\x12\n\npixelWidth\x18\x02 \x01(\r\x12\x13\n\x0bpixelHeight\x18\x03 \x01(\r\x12\x13\n\x0b\x64igitizedBy\x18\x08 \x01(\x0c\x12K\n\x08\x64\x65nsePng\x18\t \x01(\x0b\x32\x37.pictures.luminostics.lab.research.DenseFlattenedMatrixH\x00\x12G\n\tsparseBsr\x18\n \x01(\x0b\x32\x32.pictures.luminostics.lab.research.SparseBsrMatrixH\x00\x12V\n\rmysqlDensePng\x18\x0b \x01(\x0b\x32=.pictures.luminostics.lab.research.BinaryDenseFlattenedMatrixH\x00\x12R\n\x0emysqlSparseBsr\x18\x0c \x01(\x0b\x32\x38.pictures.luminostics.lab.research.BinarySparseBsrMatrixH\x00\x42\x10\n\x0e\x66latDataMatrixB6\n\'pictures.luminostics.lab.research.modelB\tLabImagesP\x01\x62\x06proto3'
)




_SPARSEBSRMATRIX = _descriptor.Descriptor(
  name='SparseBsrMatrix',
  full_name='pictures.luminostics.lab.research.SparseBsrMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockWidth', full_name='pictures.luminostics.lab.research.SparseBsrMatrix.blockWidth', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blockHeight', full_name='pictures.luminostics.lab.research.SparseBsrMatrix.blockHeight', index=1,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indPtr', full_name='pictures.luminostics.lab.research.SparseBsrMatrix.indPtr', index=2,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indices', full_name='pictures.luminostics.lab.research.SparseBsrMatrix.indices', index=3,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='pictures.luminostics.lab.research.SparseBsrMatrix.data', index=4,
      number=10, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=162,
)


_BINARYSPARSEBSRMATRIX = _descriptor.Descriptor(
  name='BinarySparseBsrMatrix',
  full_name='pictures.luminostics.lab.research.BinarySparseBsrMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blockWidth', full_name='pictures.luminostics.lab.research.BinarySparseBsrMatrix.blockWidth', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blockHeight', full_name='pictures.luminostics.lab.research.BinarySparseBsrMatrix.blockHeight', index=1,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indPtrLen', full_name='pictures.luminostics.lab.research.BinarySparseBsrMatrix.indPtrLen', index=2,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indPtr', full_name='pictures.luminostics.lab.research.BinarySparseBsrMatrix.indPtr', index=3,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indicesLen', full_name='pictures.luminostics.lab.research.BinarySparseBsrMatrix.indicesLen', index=4,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='indices', full_name='pictures.luminostics.lab.research.BinarySparseBsrMatrix.indices', index=5,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataLen', full_name='pictures.luminostics.lab.research.BinarySparseBsrMatrix.dataLen', index=6,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='pictures.luminostics.lab.research.BinarySparseBsrMatrix.data', index=7,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=332,
)


_DENSEFLATTENEDMATRIX = _descriptor.Descriptor(
  name='DenseFlattenedMatrix',
  full_name='pictures.luminostics.lab.research.DenseFlattenedMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='pictures.luminostics.lab.research.DenseFlattenedMatrix.data', index=0,
      number=10, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=370,
)


_BINARYDENSEFLATTENEDMATRIX = _descriptor.Descriptor(
  name='BinaryDenseFlattenedMatrix',
  full_name='pictures.luminostics.lab.research.BinaryDenseFlattenedMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataLen', full_name='pictures.luminostics.lab.research.BinaryDenseFlattenedMatrix.dataLen', index=0,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='pictures.luminostics.lab.research.BinaryDenseFlattenedMatrix.data', index=1,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=431,
)


_XMPHEADERCONTENT = _descriptor.Descriptor(
  name='XmpHeaderContent',
  full_name='pictures.luminostics.lab.research.XmpHeaderContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='pictures.luminostics.lab.research.XmpHeaderContent.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataType', full_name='pictures.luminostics.lab.research.XmpHeaderContent.dataType', index=1,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='captureTime', full_name='pictures.luminostics.lab.research.XmpHeaderContent.captureTime', index=2,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='captureDelay', full_name='pictures.luminostics.lab.research.XmpHeaderContent.captureDelay', index=3,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exposureTime', full_name='pictures.luminostics.lab.research.XmpHeaderContent.exposureTime', index=4,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=548,
)


_IMAGESAMPLECONTAINER = _descriptor.Descriptor(
  name='ImageSampleContainer',
  full_name='pictures.luminostics.lab.research.ImageSampleContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='pictures.luminostics.lab.research.ImageSampleContainer.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pixelWidth', full_name='pictures.luminostics.lab.research.ImageSampleContainer.pixelWidth', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pixelHeight', full_name='pictures.luminostics.lab.research.ImageSampleContainer.pixelHeight', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='digitizedBy', full_name='pictures.luminostics.lab.research.ImageSampleContainer.digitizedBy', index=3,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='densePng', full_name='pictures.luminostics.lab.research.ImageSampleContainer.densePng', index=4,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sparseBsr', full_name='pictures.luminostics.lab.research.ImageSampleContainer.sparseBsr', index=5,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mysqlDensePng', full_name='pictures.luminostics.lab.research.ImageSampleContainer.mysqlDensePng', index=6,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mysqlSparseBsr', full_name='pictures.luminostics.lab.research.ImageSampleContainer.mysqlSparseBsr', index=7,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='flatDataMatrix', full_name='pictures.luminostics.lab.research.ImageSampleContainer.flatDataMatrix',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=551,
  serialized_end=1044,
)

_IMAGESAMPLECONTAINER.fields_by_name['header'].message_type = _XMPHEADERCONTENT
_IMAGESAMPLECONTAINER.fields_by_name['densePng'].message_type = _DENSEFLATTENEDMATRIX
_IMAGESAMPLECONTAINER.fields_by_name['sparseBsr'].message_type = _SPARSEBSRMATRIX
_IMAGESAMPLECONTAINER.fields_by_name['mysqlDensePng'].message_type = _BINARYDENSEFLATTENEDMATRIX
_IMAGESAMPLECONTAINER.fields_by_name['mysqlSparseBsr'].message_type = _BINARYSPARSEBSRMATRIX
_IMAGESAMPLECONTAINER.oneofs_by_name['flatDataMatrix'].fields.append(
  _IMAGESAMPLECONTAINER.fields_by_name['densePng'])
_IMAGESAMPLECONTAINER.fields_by_name['densePng'].containing_oneof = _IMAGESAMPLECONTAINER.oneofs_by_name['flatDataMatrix']
_IMAGESAMPLECONTAINER.oneofs_by_name['flatDataMatrix'].fields.append(
  _IMAGESAMPLECONTAINER.fields_by_name['sparseBsr'])
_IMAGESAMPLECONTAINER.fields_by_name['sparseBsr'].containing_oneof = _IMAGESAMPLECONTAINER.oneofs_by_name['flatDataMatrix']
_IMAGESAMPLECONTAINER.oneofs_by_name['flatDataMatrix'].fields.append(
  _IMAGESAMPLECONTAINER.fields_by_name['mysqlDensePng'])
_IMAGESAMPLECONTAINER.fields_by_name['mysqlDensePng'].containing_oneof = _IMAGESAMPLECONTAINER.oneofs_by_name['flatDataMatrix']
_IMAGESAMPLECONTAINER.oneofs_by_name['flatDataMatrix'].fields.append(
  _IMAGESAMPLECONTAINER.fields_by_name['mysqlSparseBsr'])
_IMAGESAMPLECONTAINER.fields_by_name['mysqlSparseBsr'].containing_oneof = _IMAGESAMPLECONTAINER.oneofs_by_name['flatDataMatrix']
DESCRIPTOR.message_types_by_name['SparseBsrMatrix'] = _SPARSEBSRMATRIX
DESCRIPTOR.message_types_by_name['BinarySparseBsrMatrix'] = _BINARYSPARSEBSRMATRIX
DESCRIPTOR.message_types_by_name['DenseFlattenedMatrix'] = _DENSEFLATTENEDMATRIX
DESCRIPTOR.message_types_by_name['BinaryDenseFlattenedMatrix'] = _BINARYDENSEFLATTENEDMATRIX
DESCRIPTOR.message_types_by_name['XmpHeaderContent'] = _XMPHEADERCONTENT
DESCRIPTOR.message_types_by_name['ImageSampleContainer'] = _IMAGESAMPLECONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SparseBsrMatrix = _reflection.GeneratedProtocolMessageType('SparseBsrMatrix', (_message.Message,), {
  'DESCRIPTOR' : _SPARSEBSRMATRIX,
  '__module__' : 'sample_image_pb2'
  # @@protoc_insertion_point(class_scope:pictures.luminostics.lab.research.SparseBsrMatrix)
  })
_sym_db.RegisterMessage(SparseBsrMatrix)

BinarySparseBsrMatrix = _reflection.GeneratedProtocolMessageType('BinarySparseBsrMatrix', (_message.Message,), {
  'DESCRIPTOR' : _BINARYSPARSEBSRMATRIX,
  '__module__' : 'sample_image_pb2'
  # @@protoc_insertion_point(class_scope:pictures.luminostics.lab.research.BinarySparseBsrMatrix)
  })
_sym_db.RegisterMessage(BinarySparseBsrMatrix)

DenseFlattenedMatrix = _reflection.GeneratedProtocolMessageType('DenseFlattenedMatrix', (_message.Message,), {
  'DESCRIPTOR' : _DENSEFLATTENEDMATRIX,
  '__module__' : 'sample_image_pb2'
  # @@protoc_insertion_point(class_scope:pictures.luminostics.lab.research.DenseFlattenedMatrix)
  })
_sym_db.RegisterMessage(DenseFlattenedMatrix)

BinaryDenseFlattenedMatrix = _reflection.GeneratedProtocolMessageType('BinaryDenseFlattenedMatrix', (_message.Message,), {
  'DESCRIPTOR' : _BINARYDENSEFLATTENEDMATRIX,
  '__module__' : 'sample_image_pb2'
  # @@protoc_insertion_point(class_scope:pictures.luminostics.lab.research.BinaryDenseFlattenedMatrix)
  })
_sym_db.RegisterMessage(BinaryDenseFlattenedMatrix)

XmpHeaderContent = _reflection.GeneratedProtocolMessageType('XmpHeaderContent', (_message.Message,), {
  'DESCRIPTOR' : _XMPHEADERCONTENT,
  '__module__' : 'sample_image_pb2'
  # @@protoc_insertion_point(class_scope:pictures.luminostics.lab.research.XmpHeaderContent)
  })
_sym_db.RegisterMessage(XmpHeaderContent)

ImageSampleContainer = _reflection.GeneratedProtocolMessageType('ImageSampleContainer', (_message.Message,), {
  'DESCRIPTOR' : _IMAGESAMPLECONTAINER,
  '__module__' : 'sample_image_pb2'
  # @@protoc_insertion_point(class_scope:pictures.luminostics.lab.research.ImageSampleContainer)
  })
_sym_db.RegisterMessage(ImageSampleContainer)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
